7.0.2
* Translated using Weblate (Polish (pl_pl))

Currently translated at 100.0% (301 of 301 strings)

Co-authored-by: Jacek <jacek-bydgoszcz@o2.pl>
Translate-URL: https://kodi.weblate.cloud/projects/kodi-add-ons-video/plugin-video-youtube/pl_pl/
Translation: Kodi add-ons: video/plugin.video.youtube

* Use an Android YouTube app User-Agent and payload

* cleanup

* 7.0.2~alpha3

* add break for successful attempt

* Fixes for content not available error

- Update UA
- Update request URL
- Update payload content
- Update client details and add additional client fallbacks
- Improve fallback handling

* Code tidy up

* Don't always try fallbacks on error response

- Only attempt if client version is blocked (too old)

* Fix for error reason check using translatable text

* Add code comments

* Add additional client fallbacks

* Add additional status checks

* Fix KeyError on exhaustion of 2nd set of fallbacks

* Workaround for certain fallbacks not having url

- signatureCipher is present instead and needs to be deciphered

* 7.0.2~alpha4

* Update client fallbacks

* Add signature deciphering for WEB_CREATOR client

* Add range query param to stream urls

* Fix trying string operation when url is not found

* Added advanced option to choose alternate client

* Make default range query parameter open ended

* Short circuit check for signatureCipher

* 7.0.2~alpha5

* Update to handle client/header pairs

- Match client and header details from other popular third party tools/clients
- Simplify previously added signaturCipher handling
- Also add existing nsig rate bypass handling back in (currently not fully working)

* Update client/header selection

* Update broken signature cipher handling

* Tidy up and add extra debug logging

* 7.0.2~alpha6

* Translated using Weblate (Polish (pl_pl))

Currently translated at 100.0% (302 of 302 strings)

Translated using Weblate (Korean (ko_kr))

Currently translated at 100.0% (302 of 302 strings)

Translated using Weblate (Italian (it_it))

Currently translated at 100.0% (302 of 302 strings)

Translated using Weblate (Spanish (Spain) (es_es))

Currently translated at 100.0% (302 of 302 strings)

Update translation files

Updated by "Update PO files to match POT (msgmerge)" hook in Weblate.

Translated using Weblate (Chinese (China) (zh_cn))

Currently translated at 100.0% (301 of 301 strings)

Translated using Weblate (Italian (it_it))

Currently translated at 100.0% (301 of 301 strings)

Co-authored-by: Hosted Weblate <hosted@weblate.org>
Co-authored-by: José Antonio Alvarado <jalvarado0.eses@gmail.com>
Co-authored-by: Marek Adamski <fevbew@wp.pl>
Co-authored-by: Massimo Pissarello <mapi68@gmail.com>
Co-authored-by: Minho Park <parkmino@gmail.com>
Co-authored-by: NicoYazawa <1161118059@qq.com>
Translate-URL: https://kodi.weblate.cloud/projects/kodi-add-ons-video/plugin-video-youtube/
Translate-URL: https://kodi.weblate.cloud/projects/kodi-add-ons-video/plugin-video-youtube/es_es/
Translate-URL: https://kodi.weblate.cloud/projects/kodi-add-ons-video/plugin-video-youtube/it_it/
Translate-URL: https://kodi.weblate.cloud/projects/kodi-add-ons-video/plugin-video-youtube/ko_kr/
Translate-URL: https://kodi.weblate.cloud/projects/kodi-add-ons-video/plugin-video-youtube/pl_pl/
Translate-URL: https://kodi.weblate.cloud/projects/kodi-add-ons-video/plugin-video-youtube/zh_cn/
Translation: Kodi add-ons: video/plugin.video.youtube

* Add more setting options to change clients

* Fixes for subtitles having a relative path

* Add individual innertube api keys for clients

* Elevate level of log messages

* Update client details

- Remove non-working clients
- Add new HDR capable default client

* Change added logging to debug level

* Update translation files

Updated by "Update PO files to match POT (msgmerge)" hook in Weblate.

Co-authored-by: Hosted Weblate <hosted@weblate.org>
Translate-URL: https://kodi.weblate.cloud/projects/kodi-add-ons-video/plugin-video-youtube/
Translation: Kodi add-ons: video/plugin.video.youtube

* 7.0.2~alpha7

* Add non-adaptive format android client as a backup

- Default client selection prioritises resolution and HDR
- Alternate #1 prioritises subtitles
- Alternate #2 prioritises resolution

* Fix 403 forbidden error using android client

- Enable adaptive formats
- Add as first priority

* Initial stream selection re-write

- Not well tested and known to not work correctly

* Remove unused code

* Make normalize function a staticmethod

* Translated using Weblate (Polish (pl_pl))

Currently translated at 100.0% (304 of 304 strings)

Translated using Weblate (Italian (it_it))

Currently translated at 100.0% (304 of 304 strings)

Translated using Weblate (Spanish (Spain) (es_es))

Currently translated at 100.0% (304 of 304 strings)

Co-authored-by: José Antonio Alvarado <jalvarado0.eses@gmail.com>
Co-authored-by: Marek Adamski <fevbew@wp.pl>
Co-authored-by: Massimo Pissarello <mapi68@gmail.com>
Translate-URL: https://kodi.weblate.cloud/projects/kodi-add-ons-video/plugin-video-youtube/es_es/
Translate-URL: https://kodi.weblate.cloud/projects/kodi-add-ons-video/plugin-video-youtube/it_it/
Translate-URL: https://kodi.weblate.cloud/projects/kodi-add-ons-video/plugin-video-youtube/pl_pl/
Translation: Kodi add-ons: video/plugin.video.youtube

* Update client priorities and comments

* Fix potential TypeError when sort key is missing

* Short-circuit retries when geo-blocked

* Update stream selections

- Match audio and video containers
- Properly check for IA compatibility
- Properly check for HDR enabled/disabled
- Properly sort HDR enabled streams
- Adjust <Role/> value based on stream selection
- This is not as robust as the old method but is simpler/quicker

* Tidy up

* Translated using Weblate (Italian (it_it))

Currently translated at 100.0% (304 of 304 strings)

Translated using Weblate (Danish (da_dk))

Currently translated at 100.0% (304 of 304 strings)

Translated using Weblate (Korean (ko_kr))

Currently translated at 100.0% (304 of 304 strings)

Translated using Weblate (Italian (it_it))

Currently translated at 100.0% (304 of 304 strings)

Co-authored-by: Christian Gade <gade@kodi.tv>
Co-authored-by: Hosted Weblate <hosted@weblate.org>
Co-authored-by: Massimo Pissarello <mapi68@gmail.com>
Co-authored-by: Minho Park <parkmino@gmail.com>
Translate-URL: https://kodi.weblate.cloud/projects/kodi-add-ons-video/plugin-video-youtube/da_dk/
Translate-URL: https://kodi.weblate.cloud/projects/kodi-add-ons-video/plugin-video-youtube/it_it/
Translate-URL: https://kodi.weblate.cloud/projects/kodi-add-ons-video/plugin-video-youtube/ko_kr/
Translation: Kodi add-ons: video/plugin.video.youtube

* Remove redundant checks

* Update stream selection for multi-language videos

- Fixes default and original audio selection
- Fixes identification/selection of multi-channel audio
- Fixes identification/selection of multi-language audio
- Fixes selection of higher quality audio from non-matching containers
- Fixes edge-cases where selected stream doesn't match label in selection dialog

* fix: Limit host connections getting subscription feeds

When attempting to view My Subscriptions some users are reporting they
are unable to see any results with following errors in logs:

    ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:997)

This is a result on certain systems of attempting to fetch too many
subscription channels (~50 or more) since the current code generates a
thread and connection for every channel feed.

Fixed using a requests session to reuse the connection and setting a
maximum pool size of 5 with blocking enabled to prevent new connections.
There is also a speedup from limiting the pool size (0.5s vs 5s) and the
selected pool size seems a good compromise.

Fixes: https://github.com/anxdpanic/plugin.video.youtube/issues/280

* Update itag format details

* Fix logging error without response

* Store selected client and header details

* Additional request for captions for clients that dont provide them

* Make check for geo-blocked video errors less specific

* Make case of stream title consistent with other titles

* Fix possible regression in capability evaluation

- The meaning of None has changed a few times (#127, #146)
- Add comment to define possible values
- Vorbis audio doesn't seem to be offered by Youtube anymore
- Vorbis appears to have been supported by ISA for a long time

* Enable HLS and adaptive HLS live streams

* Remove disable_dash client property

* Allow HDR when Adaptive MP4 video is selected

* Update server request log messages

* Add default IP param to IP address setting getter

* Add some basic error handling for https session

* Implement original single stream live HLS playback

* Fix live stream settings options when MPD disabled

* Remove Authorisation header from HLS request

- Header is not needed as url has already been retrieved using API

* Fix age gate setting not being applied

* Fail earlier if playback is not possible

* Make lang attribute value conform to MPD specs

Also display language in stream quality selector

* Improve handling of dubbed and descriptive audio

Also align MPD manifest with spec and ISA quirks

* Further improve stream labelling

- Use custom video label (Youtube qualityLabel is not accurate)
- Avoid duplicate tokens (from ISA and Youtube descriptions)
- Provide bitrate of audio stream per AdaptationSet (not shown by ISA)

* Remove conditions for 30 fps limit setting

- Should not be linked to HDR setting as there are non-HDR HFR itags
- Should not be disabled if a preferred container is selected

* Improve selection and display of video resolution

- Correctly handles portrait videos
- Correctly handles ultra wide AR videos
- Code is messy due to backwards compatibility with quality settings

* Fix sorting of audio in stream selection dialog

* Update ISA capabilities map and simplify matching

* Improve labelling of more odd video resolutions

* Improve MPD sorting and default quality selection

- This won't fix incorrect ordering by ISA for manual selection
- ISA performs it's own simple sorting that results in H264 being preferred over better AV1 streams

* Standardise/change "dash" in names to "mpd"

* Fix evaluation of single ISA capability

* Improve stream quality and features selection

* Standardise setting attribute order

* Improve MPD manifest language sorting

- ISA will still override this and sort by bandwidth

* Fix incorrect return on create directory failure

* Fix sorting of stream chooser

Sorts based on:
- quality
- preferred language
- original language
- language name (in English...)

* Move get_language_name to kodion context class

* Fix sorting of ISA audio chooser

- Also improve visibility of stream details
- Details in square brackets are max quality level of an adaptive stream
- Streams without square brackets have a single fixed quality level
- Duplication of language in name is unavoidable

* Fix filtering streams when auto selection disabled

* Code tidy up

* Partially fix use history settings

- Split into local and remote history settings

* Fixes for throttling and restricted videos

* Improve client building

* Fix errors in fetching captions

* Dont copy headers if they are not being modified

* Fix json argument of _request redefining import

* Code tidy up

* Allow mulltiple params in call to _set_query_param

* Simplify and tidy up code

* Fix default caption selection

* Simplify update of MPD stream format details

* Split up _generate_mpd_manifest

-

* Use default caption language to label audio track

* Simplify language detection & show ASR indication

* Allow cookies to be used from player page request

* Translated using Weblate (Slovak (sk_sk))

Currently translated at 100.0% (304 of 304 strings)

Translated using Weblate (Catalan (Spain) (ca_es))

Currently translated at 0.9% (3 of 304 strings)

Translated using Weblate (Spanish (Spain) (es_es))

Currently translated at 100.0% (304 of 304 strings)

Translated using Weblate (Slovak (sk_sk))

Currently translated at 99.0% (301 of 304 strings)

Co-authored-by: Christian Gade <gade@kodi.tv>
Co-authored-by: Hosted Weblate <hosted@weblate.org>
Co-authored-by: Jose Riha <jose1711@gmail.com>
Co-authored-by: José Antonio Alvarado <jalvarado0.eses@gmail.com>
Co-authored-by: Patrik Špaňo <patrik.spano@gmail.com>
Translate-URL: https://kodi.weblate.cloud/projects/kodi-add-ons-video/plugin-video-youtube/ca_es/
Translate-URL: https://kodi.weblate.cloud/projects/kodi-add-ons-video/plugin-video-youtube/es_es/
Translate-URL: https://kodi.weblate.cloud/projects/kodi-add-ons-video/plugin-video-youtube/sk_sk/
Translation: Kodi add-ons: video/plugin.video.youtube

* Make request timeout a parameter of _request

TODO: Make this an advanced setting

* Fix regression with non-logged in playback

* Improve error/debug logging

* Update and tidy up client details

* Use client specific api keys

* Code tidy up

* (Re)Allow tv api key use

- Not enabled by default

* Fix for missing hls manifest url

TODO: combine different stream parsing methods to avoid duplicate code

* Fix different bitrate label vs ISA stream selector

- Also misc related tidy code tidy up

* Fix incorrect level for declaring manifest_url

* Add timeout and error handling for api requests

* Add timeout, fix incorrect args for Session.get

* Fix incorrect httpd request address

* Settings name import tidy up

* 7.0.2~alpha8

* Allow manual release workflow trigger

* Update release workflow for manual run on forks

* 7.0.2

---------

Co-authored-by: Hosted Weblate <hosted@weblate.org>
Co-authored-by: Jacek <jacek-bydgoszcz@o2.pl>
Co-authored-by: anxdpanic <anxdpanic@users.noreply.github.com>
Co-authored-by: RNavega <rafanavega@hotmail.com>
Co-authored-by: Chad Wagner <47257594+wagnerch@users.noreply.github.com>
Co-authored-by: José Antonio Alvarado <jalvarado0.eses@gmail.com>
Co-authored-by: Marek Adamski <fevbew@wp.pl>
Co-authored-by: Massimo Pissarello <mapi68@gmail.com>
Co-authored-by: Minho Park <parkmino@gmail.com>
Co-authored-by: NicoYazawa <1161118059@qq.com>
Co-authored-by: Christian Gade <gade@kodi.tv>
Co-authored-by: Calum Lind <calumlind@gmail.com>
Co-authored-by: Jose Riha <jose1711@gmail.com>
Co-authored-by: Patrik Špaňo <patrik.spano@gmail.com>